# Generated by Django 4.2.2 on 2024-08-02 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_add_post", "Can add post"),
                    ("can_change_post", "Can change post"),
                    ("can_delete_post", "Can delete post"),
                ],
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
    ]
