# Generated by Django 4.2.2 on 2024-08-02 19:19

import autoslug.fields
from django.db import migrations
import slugify.slugify


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_alter_blog_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                populate_from="title",
                slugify=slugify.slugify,
                unique=True,
            ),
        ),
    ]
