# Generated by Django 4.2.2 on 2024-07-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("running", "Запущена"),
                    ("completed", "Завершена"),
                ],
                max_length=50,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
