# Generated by Django 4.2.2 on 2024-07-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0003_alter_mailing_periodicity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("running", "Запущена"),
                    ("completed", "Завершена"),
                    ("failed", "Неудача"),
                ],
                max_length=50,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
