# Generated by Django 4.2.2 on 2024-08-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0005_client_owner_mailing_owner_message_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_view_any_mailing", "Can view any mailing"),
                    ("can_disable_mailing", "Can disable mailing"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
